import { motion } from "framer-motion";
import { FileText } from "lucide-react";

const sections = [
  { title: "Acceptance of Terms", content: "By accessing or using AgentBuilder, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform." },
  { title: "Account Registration", content: "You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your credentials and all activities under your account." },
  { title: "Acceptable Use", content: "You agree not to use the platform for any unlawful purpose or in violation of any applicable laws. Automated scraping, abuse of API rate limits, and distribution of harmful content are prohibited." },
  { title: "AI Agent Output", content: "You retain ownership of your prompts and agent configurations. Output generated by AI models is provided as-is and should be reviewed before use. We are not responsible for the accuracy or appropriateness of AI-generated content." },
  { title: "Service Level", content: "We strive for 99.9% uptime but do not guarantee uninterrupted service. The platform is provided 'as is' without warranties of any kind." },
  { title: "Limitation of Liability", content: "AgentBuilder shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform." },
  { title: "Termination", content: "We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior. You may terminate your account at any time." },
  { title: "Changes to Terms", content: "We may modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms." },
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-3xl px-4 py-20 sm:px-6 lg:px-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex items-center gap-2 text-primary mb-4">
            <FileText size={20} />
            <span className="text-xs font-bold uppercase tracking-widest">Terms</span>
          </div>
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground mb-2">Last updated: May 11, 2026</p>
          <p className="text-sm text-muted-foreground mb-12">Please read these terms carefully before using AgentBuilder.</p>
        </motion.div>

        <div className="space-y-8">
          {sections.map((section, i) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.06 }}
            >
              <h2 className="text-lg font-bold mb-2">{i + 1}. {section.title}</h2>
              <p className="text-sm text-muted-foreground leading-7">{section.content}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
